### ISSUE TITLE
大神好，提示您在 /var/spool/mail/root 中有新邮件

### ISSUE THREAD

**Issue by orgccav** [EvineDeng/jd-base#10]
麻烦大神帮忙看看，提示语法错误 !(async () => {。

From root@111.111.111.111.16clouds.com  Fri Oct 30 14:20:01 2020
Return-Path: <root@111.111.111.111.16clouds.com>
X-Original-To: root
Delivered-To: root@111.111.111.111.16clouds.com
Received: by 111.111.111.111.16clouds.com (Postfix, from userid 0)
	id ABEEE13BE; Fri, 30 Oct 2020 14:20:01 +0800 (CST)
From: "(Cron Daemon)" <root@111.111.111.111.16clouds.com>
To: root@111.111.111.111.16clouds.com
Subject: Cron <root@97> /root/shell/jd_joy_feedPets.sh
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=101>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/0>
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <USER=root>
Message-Id: <20201030062001.ABEEE13BE@111.111.111.111.16clouds.com>
Date: Fri, 30 Oct 2020 14:20:01 +0800 (CST)

/root/scripts/jd_joy_feedPets.js:41
!(async () => {
        ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

From root@111.111.111.111.16clouds.com  Fri Oct 30 14:30:02 2020
Return-Path: <root@111.111.111.111.16clouds.com>
X-Original-To: root
Delivered-To: root@111.111.111.111.16clouds.com
Received: by 111.111.111.111.16clouds.com (Postfix, from userid 0)
	id EFC3113BE; Fri, 30 Oct 2020 14:30:01 +0800 (CST)
From: "(Cron Daemon)" <root@111.111.111.111.16clouds.com>
To: root@111.111.111.111.16clouds.com
Subject: Cron <root@97> /root/shell/jd_collectProduceScore.sh
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=102>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/0>
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <USER=root>
Message-Id: <20201030063001.EFC3113BE@111.111.111.111.16clouds.com>
Date: Fri, 30 Oct 2020 14:30:01 +0800 (CST)

/root/scripts/jd_collectProduceScore.js:26
!(async () => {
        ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

From root@111.111.111.111.16clouds.com  Fri Oct 30 14:40:02 2020
Return-Path: <root@111.111.111.111.16clouds.com>
X-Original-To: root
Delivered-To: root@111.111.111.111.16clouds.com
Received: by 111.111.111.111.16clouds.com (Postfix, from userid 0)
	id 39EF913C0; Fri, 30 Oct 2020 14:40:02 +0800 (CST)
From: "(Cron Daemon)" <root@111.111.111.111.16clouds.com>
To: root@111.111.111.111.16clouds.com
Subject: Cron <root@97> /root/shell/jd_joy_feedPets.sh
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=103>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/0>
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <USER=root>
Message-Id: <20201030064002.39EF913C0@111.111.111.111.16clouds.com>
Date: Fri, 30 Oct 2020 14:40:02 +0800 (CST)

/root/scripts/jd_joy_feedPets.js:41
!(async () => {
        ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

**Comment by EvineDeng** [comment]
不知道你填的东西是啥，也不知道你是不是按流程操作的，没有更多的信息无法判断。

**Comment by P2Baby** [comment]
echo "unset MAILCHECK" >> /etc/profile
