### ISSUE TITLE
种豆得豆 API请求失败

### ISSUE THREAD

**Issue by JesseTzh** [EvineDeng/jd-base#138]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：docker v3

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：种豆得豆log中出现报错

### (2) 详细日志
A：
```
{"name":"HTTPError","timings":{"start":1608647809800,"socket":1608647809800,"lookup":1608647809801,"connect":1608647811099,"upload":1608647811099,"response":1608647924966,"end":1608647924967,"phases":{"wait":0,"dns":1,"tcp":1298,"request":0,"firstByte":113867,"download":1,"total":115167}}}
京东种豆得豆 API请求失败，请检查网路重试
```
以及也会出现
```
❗️京东种豆得豆, 错误!
RequestError: getaddrinfo EAI_AGAIN api.m.jd.com
    at ClientRequest.<anonymous> (/jd/scripts/node_modules/got/dist/source/core/index.js:953:111)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/jd/scripts/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)

❌ 京东种豆得豆, 失败! 原因: TypeError: Cannot read property 'code' of undefined!
```
翻阅日志后发现不定时出现
如果只是网络问题烦请关闭此Issues

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
与我脚本无关。

**Comment by zhangxu2814** [comment]
自动上车还搞吗？
用你原来的改了一版，在运行的时候实体机卡顿。

**Comment by jarryyen** [comment]
我这里也是....而且好几个项目都报错....
