### ISSUE TITLE
大佬您好，能重写脚本失效功能吗

### ISSUE THREAD

**Issue by lan-tianxiang** [EvineDeng/jd-base#27]

**Comment by lan-tianxiang** [comment]
有的脚本具有时效性呢

**Comment by EvineDeng** [comment]
https://github.com/EvineDeng/jd-base/issues/26

**Comment by lan-tianxiang** [comment]
> #26
刚刚运行了一下，还是不行
![image](https://user-images.githubusercontent.com/42911023/98624466-d8fcdd80-2348-11eb-97e4-958a3623c8ae.png)

我建议这样修改first_run就行了

git clone https://gitee.com/lxk0301/scripts scripts
![image](https://user-images.githubusercontent.com/42911023/98625032-e8c8f180-2349-11eb-850b-be4045c7a373.png)

**Comment by lan-tianxiang** [comment]
测试了一下，没有问题了

**Comment by aloasut** [comment]
现在的问题：
1.sh git_pull.sh 每次都需要输入账号密码
2.脚本运行错误
 ~/shell # sh jd_fruit.sh.sh 
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module '/root/scripts/jd_fruit.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
~/shell # sh jd_joy.sh 
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module '/root/scripts/jd_joy.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by lan-tianxiang** [comment]
必须要先删除原来的scripts&nbsp; 因为原来的库被Ban了,或者用git remote也行。
这样吧，我把修改后的项目上传上来你看一下
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "aloasut"; 
Date: 2020年11月10日(星期二) 中午12:22
To: "EvineDeng/jd-base"; 
Cc: "lan-tianxiang"; "Author"; 
Subject: Re: [EvineDeng/jd-base] 大佬您好，能重写脚本失效功能吗 (#27)

&nbsp;


 
现在的问题：
 1.sh git_pull.sh 每次都需要输入账号密码
 2.脚本运行错误
 ~/shell # sh jd_fruit.sh.sh
 internal/modules/cjs/loader.js:834
 throw err;
 ^
 
Error: Cannot find module '/root/scripts/jd_fruit.js'
 at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
 at Function.Module._load (internal/modules/cjs/loader.js:687:27)
 at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
 at internal/main/run_main_module.js:17:47 {
 code: 'MODULE_NOT_FOUND',
 requireStack: []
 }
 ~/shell # sh jd_joy.sh
 internal/modules/cjs/loader.js:834
 throw err;
 ^
 
Error: Cannot find module '/root/scripts/jd_joy.js'
 at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
 at Function.Module._load (internal/modules/cjs/loader.js:687:27)
 at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
 at internal/main/run_main_module.js:17:47 {
 code: 'MODULE_NOT_FOUND',
 requireStack: []
 }

**Comment by EvineDeng** [comment]
已经全部按新库改好了，删除原来的容器和镜像，重新按readme配置下吧，这个issue先关闭了。

**Comment by lan-tianxiang** [comment]
https://github.com/lan-tianxiang/EvineDeng-jd-base&nbsp; &nbsp;看看这样
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "EvineDeng"; 
Date: 2020年11月10日(星期二) 中午1:43
To: "EvineDeng/jd-base"; 
Cc: "lan-tianxiang"; "Author"; 
Subject: Re: [EvineDeng/jd-base] 大佬您好，能重写脚本失效功能吗 (#27)

&nbsp;


 
已经全部按新库改好了，删除原来的容器和镜像，重新按readme配置下吧，这个issue先关闭了。
