### ISSUE TITLE
网页编辑服务无法访问和一直后台运似和jd_crazy_joy_coin服务是无法同时运行的是吗？

### ISSUE THREAD

**Issue by hs20073** [EvineDeng/jd-base#298]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：Openwrt 5.4.86

## 3. 按照以下哪个教程做的

- [x ] Linux
- [ ] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：
1.在OpenWrt部署，网页编辑用node server.js指令能正常访问，pm2 start server.js指令无法访问
2.一直后台运行貌似和jd_crazy_joy_coin服务是无法同时运行的是吗？

### (2) 详细日志
A：
root@451D-OpenWrt:/home/hs/jd/panel# pm2 start server.js
[PM2] Starting /home/hs/jd/panel/server.js in fork_mode (1 instance)
[PM2] Done.
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 0  │ jd_crazy_joy_coin  │ fork     │ 15   │ errored   │ 0%       │ 0b       │
│ 1  │ server             │ fork     │ 0    │ online    │ 0%       │ 15.9mb   │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘

### (1) Node.js版本

A：v14.15.4

### (2) npm版本

A：6.14.10

### (3)npm install的日志

A：
audited 206 packages in 3.881s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by EvineDeng** [comment]
可以一起运行。

**Comment by hs20073** [comment]
> 可以一起运行。

报错唉
![微信截图_20210124163434](https://user-images.githubusercontent.com/8945654/105626405-52956980-5e6a-11eb-8208-8f93e91dcada.png)

**Comment by hs20073** [comment]
root@451D-OpenWrt:/home/hs/jd/panel# npm install -g pm2
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
/usr/bin/pm2 -> /usr/lib/node_modules/pm2/bin/pm2
/usr/bin/pm2-dev -> /usr/lib/node_modules/pm2/bin/pm2-dev
/usr/bin/pm2-docker -> /usr/lib/node_modules/pm2/bin/pm2-docker
/usr/bin/pm2-runtime -> /usr/lib/node_modules/pm2/bin/pm2-runtime
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/pm2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
+ pm2@4.5.1
updated 1 package in 10.428s

**Comment by hs20073** [comment]
root@451D-OpenWrt:/home/hs/jd/panel# npm install || npm install --registry=https
://registry.npm.taobao.org
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN panel No description
npm WARN panel No repository field.
npm WARN panel No license field.

**Comment by hs20073** [comment]
root@451D-OpenWrt:/home/hs/jd/panel# pm2 log
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2021-01-24T17:05:59: PM2 log: App [jd_crazy_joy_coin:0] online
PM2        | 2021-01-24T17:06:00: PM2 log: App [jd_crazy_joy_coin:0] exited with code [1] via signal [SIGINT]
PM2        | 2021-01-24T17:06:00: PM2 log: App [jd_crazy_joy_coin:0] starting in -fork mode-
PM2        | 2021-01-24T17:06:00: PM2 log: App [jd_crazy_joy_coin:0] online
PM2        | 2021-01-24T17:06:00: PM2 log: App [jd_crazy_joy_coin:0] exited with code [1] via signal [SIGINT]
PM2        | 2021-01-24T17:06:00: PM2 log: App [jd_crazy_joy_coin:0] starting in -fork mode-
PM2        | 2021-01-24T17:06:00: PM2 log: App [jd_crazy_joy_coin:0] online
PM2        | 2021-01-24T17:06:00: PM2 log: App [jd_crazy_joy_coin:0] exited with code [1] via signal [SIGINT]
PM2        | 2021-01-24T17:06:00: PM2 log: App [jd_crazy_joy_coin:0] starting in -fork mode-
PM2        | 2021-01-24T17:06:00: PM2 log: App [jd_crazy_joy_coin:0] online
PM2        | 2021-01-24T17:06:01: PM2 log: App [jd_crazy_joy_coin:0] exited with code [1] via signal [SIGINT]
PM2        | 2021-01-24T17:06:01: PM2 log: App [jd_crazy_joy_coin:0] starting in -fork mode-
PM2        | 2021-01-24T17:06:01: PM2 log: App [jd_crazy_joy_coin:0] online
PM2        | 2021-01-24T17:06:01: PM2 log: App [jd_crazy_joy_coin:0] exited with code [1] via signal [SIGINT]
PM2        | 2021-01-24T17:06:01: PM2 log: Script /home/hs/jd/scripts/jd_crazy_joy_coin.js had too many unstable restarts (16). Stopped. "errored"

/root/.pm2/logs/jd-crazy-joy-coin-out.log last 15 lines:
/root/.pm2/logs/server-out.log last 15 lines:
/root/.pm2/logs/server-error.log last 15 lines:
/root/.pm2/logs/jd-crazy-joy-coin-error.log last 15 lines:
0|jd_crazy |   ^
0|jd_crazy |
0|jd_crazy | Error [ERR_INSPECTOR_NOT_AVAILABLE]: Inspector is not available
0|jd_crazy |     at inspector.js:25:9
0|jd_crazy |     at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:283:7)
0|jd_crazy |     at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:225:10)
0|jd_crazy |     at loadNativeModule (internal/modules/cjs/helpers.js:35:9)
0|jd_crazy |     at Function.Module._load (internal/modules/cjs/loader.js:740:15)
0|jd_crazy |     at Module.require (internal/modules/cjs/loader.js:952:19)
0|jd_crazy |     at require (internal/modules/cjs/helpers.js:88:18)
0|jd_crazy |     at Object.<anonymous> (/usr/lib/node_modules/pm2/node_modules/@pm2/io/build/main/services/inspector.js:3:19)
0|jd_crazy |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
0|jd_crazy |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
0|jd_crazy |   code: 'ERR_INSPECTOR_NOT_AVAILABLE'
0|jd_crazy | }

**Comment by hs20073** [comment]
root@451D-OpenWrt:/home/hs/jd/panel# pm2 start server.js
[PM2] Applying action restartProcessId on app [server](ids: [ 1 ])
[PM2] [server](1) ✓
[PM2] Process successfully started
┌──────────────────────────────────────────────────────────────────────────────
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├──────────────────────────────────────────────────────────────────────────────
│ 0  │ jd_crazy_joy_coin  │ fork     │ 30   │ errored   │ 0%       │ 0b       │
│ 1  │ server             │ fork     │ 15   │ online    │ 0%       │ 16.0mb   │
└──────────────────────────────────────────────────────────────────────────────
root@451D-OpenWrt:/home/hs/jd/panel# pm2 log
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2021-01-24T19:41:22: PM2 log: App [server:1] exited with code [1] via signal [SIGINT]
PM2        | 2021-01-24T19:41:22: PM2 log: App [server:1] starting in -fork mode-
PM2        | 2021-01-24T19:41:22: PM2 log: App [server:1] online
PM2        | 2021-01-24T19:41:22: PM2 log: App [server:1] exited with code [1] via signal [SIGINT]
PM2        | 2021-01-24T19:41:22: PM2 log: App [server:1] starting in -fork mode-
PM2        | 2021-01-24T19:41:22: PM2 log: App [server:1] online
PM2        | 2021-01-24T19:41:23: PM2 log: App [server:1] exited with code [1] via signal [SIGINT]
PM2        | 2021-01-24T19:41:23: PM2 log: App [server:1] starting in -fork mode-
PM2        | 2021-01-24T19:41:23: PM2 log: App [server:1] online
PM2        | 2021-01-24T19:41:24: PM2 log: App [server:1] exited with code [1] via signal [SIGINT]
PM2        | 2021-01-24T19:41:24: PM2 log: App [server:1] starting in -fork mode-
PM2        | 2021-01-24T19:41:24: PM2 log: App [server:1] online
PM2        | 2021-01-24T19:41:24: PM2 log: App [server:1] exited with code [1] via signal [SIGINT]
PM2        | 2021-01-24T19:41:24: PM2 log: App [server:1] starting in -fork mode-
PM2        | 2021-01-24T19:41:24: PM2 log: App [server:1] online

/root/.pm2/logs/jd-crazy-joy-coin-out.log last 15 lines:
/root/.pm2/logs/server-out.log last 15 lines:
/root/.pm2/logs/jd-crazy-joy-coin-error.log last 15 lines:
0|jd_crazy |   ^
0|jd_crazy |
0|jd_crazy | Error [ERR_INSPECTOR_NOT_AVAILABLE]: Inspector is not available
0|jd_crazy |     at inspector.js:25:9
0|jd_crazy |     at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:283:7)
0|jd_crazy |     at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:225:10)
0|jd_crazy |     at loadNativeModule (internal/modules/cjs/helpers.js:35:9)
0|jd_crazy |     at Function.Module._load (internal/modules/cjs/loader.js:740:15)
0|jd_crazy |     at Module.require (internal/modules/cjs/loader.js:952:19)
0|jd_crazy |     at require (internal/modules/cjs/helpers.js:88:18)
0|jd_crazy |     at Object.<anonymous> (/usr/lib/node_modules/pm2/node_modules/@pm2/io/build/main/services/inspector.js:3:19)
0|jd_crazy |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
0|jd_crazy |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
0|jd_crazy |   code: 'ERR_INSPECTOR_NOT_AVAILABLE'
0|jd_crazy | }

/root/.pm2/logs/server-error.log last 15 lines:
1|server   |   ^
1|server   |
1|server   | Error [ERR_INSPECTOR_NOT_AVAILABLE]: Inspector is not available
1|server   |     at inspector.js:25:9
1|server   |     at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:283:7)
1|server   |     at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:225:10)
1|server   |     at loadNativeModule (internal/modules/cjs/helpers.js:35:9)
1|server   |     at Function.Module._load (internal/modules/cjs/loader.js:740:15)
1|server   |     at Module.require (internal/modules/cjs/loader.js:952:19)
1|server   |     at require (internal/modules/cjs/helpers.js:88:18)
1|server   |     at Object.<anonymous> (/usr/lib/node_modules/pm2/node_modules/@pm2/io/build/main/services/inspector.js:3:19)
1|server   |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
1|server   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
1|server   |   code: 'ERR_INSPECTOR_NOT_AVAILABLE'
1|server   | }

1|server  | inspector.js:25
1|server  |   throw new ERR_INSPECTOR_NOT_AVAILABLE();
1|server  |   ^
1|server  | Error [ERR_INSPECTOR_NOT_AVAILABLE]: Inspector is not available
1|server  |     at inspector.js:25:9
1|server  |     at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:283:7)
1|server  |     at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:225:10)
1|server  |     at loadNativeModule (internal/modules/cjs/helpers.js:35:9)
1|server  |     at Function.Module._load (internal/modules/cjs/loader.js:740:15)
1|server  |     at Module.require (internal/modules/cjs/loader.js:952:19)
1|server  |     at require (internal/modules/cjs/helpers.js:88:18)
1|server  |     at Object.<anonymous> (/usr/lib/node_modules/pm2/node_modules/@pm2/io/build/main/services/inspector.js:3:19)
1|server  |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
1|server  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
1|server  |   code: 'ERR_INSPECTOR_NOT_AVAILABLE'
1|server  | }
PM2       | App [server:1] exited with code [1] via signal [SIGINT]
PM2       | App [server:1] starting in -fork mode-
PM2       | App [server:1] online
1|server  | inspector.js:25
1|server  |   throw new ERR_INSPECTOR_NOT_AVAILABLE();
1|server  |   ^
1|server  | Error [ERR_INSPECTOR_NOT_AVAILABLE]: Inspector is not available
1|server  |     at inspector.js:25:9
1|server  |     at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:283:7)
1|server  |     at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:225:10)
1|server  |     at loadNativeModule (internal/modules/cjs/helpers.js:35:9)
1|server  |     at Function.Module._load (internal/modules/cjs/loader.js:740:15)
1|server  |     at Module.require (internal/modules/cjs/loader.js:952:19)
1|server  |     at require (internal/modules/cjs/helpers.js:88:18)
1|server  |     at Object.<anonymous> (/usr/lib/node_modules/pm2/node_modules/@pm2/io/build/main/services/inspector.js:3:19)
1|server  |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
1|server  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
1|server  |   code: 'ERR_INSPECTOR_NOT_AVAILABLE'
1|server  | }
PM2       | App [server:1] exited with code [1] via signal [SIGINT]
PM2       | App [server:1] starting in -fork mode-
PM2       | App [server:1] online
1|server  | inspector.js:25
1|server  |   throw new ERR_INSPECTOR_NOT_AVAILABLE();
1|server  |   ^
1|server  | Error [ERR_INSPECTOR_NOT_AVAILABLE]: Inspector is not available
1|server  |     at inspector.js:25:9
1|server  |     at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:283:7)
1|server  |     at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:225:10)
1|server  |     at loadNativeModule (internal/modules/cjs/helpers.js:35:9)
1|server  |     at Function.Module._load (internal/modules/cjs/loader.js:740:15)
1|server  |     at Module.require (internal/modules/cjs/loader.js:952:19)
1|server  |     at require (internal/modules/cjs/helpers.js:88:18)
1|server  |     at Object.<anonymous> (/usr/lib/node_modules/pm2/node_modules/@pm2/io/build/main/services/inspector.js:3:19)
1|server  |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
1|server  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
1|server  |   code: 'ERR_INSPECTOR_NOT_AVAILABLE'
1|server  | }
PM2       | App [server:1] exited with code [1] via signal [SIGINT]
PM2       | App [server:1] starting in -fork mode-
PM2       | App [server:1] online
1|server  | inspector.js:25
1|server  |   throw new ERR_INSPECTOR_NOT_AVAILABLE();
1|server  |   ^
1|server  | Error [ERR_INSPECTOR_NOT_AVAILABLE]: Inspector is not available
1|server  |     at inspector.js:25:9
1|server  |     at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:283:7)
1|server  |     at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:225:10)
1|server  |     at loadNativeModule (internal/modules/cjs/helpers.js:35:9)
1|server  |     at Function.Module._load (internal/modules/cjs/loader.js:740:15)
1|server  |     at Module.require (internal/modules/cjs/loader.js:952:19)
1|server  |     at require (internal/modules/cjs/helpers.js:88:18)
1|server  |     at Object.<anonymous> (/usr/lib/node_modules/pm2/node_modules/@pm2/io/build/main/services/inspector.js:3:19)
1|server  |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
1|server  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
1|server  |   code: 'ERR_INSPECTOR_NOT_AVAILABLE'
1|server  | }
PM2       | App [server:1] exited with code [1] via signal [SIGINT]
PM2       | App [server:1] starting in -fork mode-
PM2       | App [server:1] online
1|server  | inspector.js:25
1|server  |   throw new ERR_INSPECTOR_NOT_AVAILABLE();
1|server  |   ^
1|server  | Error [ERR_INSPECTOR_NOT_AVAILABLE]: Inspector is not available
1|server  |     at inspector.js:25:9
1|server  |     at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:283:7)
1|server  |     at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:225:10)
1|server  |     at loadNativeModule (internal/modules/cjs/helpers.js:35:9)
1|server  |     at Function.Module._load (internal/modules/cjs/loader.js:740:15)
1|server  |     at Module.require (internal/modules/cjs/loader.js:952:19)
1|server  |     at require (internal/modules/cjs/helpers.js:88:18)
1|server  |     at Object.<anonymous> (/usr/lib/node_modules/pm2/node_modules/@pm2/io/build/main/services/inspector.js:3:19)
1|server  |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
1|server  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
1|server  |   code: 'ERR_INSPECTOR_NOT_AVAILABLE'
1|server  | }
PM2       | App [server:1] exited with code [1] via signal [SIGINT]
PM2       | App [server:1] starting in -fork mode-
PM2       | App [server:1] online
1|server  | inspector.js:25
1|server  |   throw new ERR_INSPECTOR_NOT_AVAILABLE();
1|server  |   ^
1|server  | Error [ERR_INSPECTOR_NOT_AVAILABLE]: Inspector is not available
1|server  |     at inspector.js:25:9
1|server  |     at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:283:7)
1|server  |     at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:225:10)
1|server  |     at loadNativeModule (internal/modules/cjs/helpers.js:35:9)
1|server  |     at Function.Module._load (internal/modules/cjs/loader.js:740:15)
1|server  |     at Module.require (internal/modules/cjs/loader.js:952:19)
1|server  |     at require (internal/modules/cjs/helpers.js:88:18)
1|server  |     at Object.<anonymous> (/usr/lib/node_modules/pm2/node_modules/@pm2/io/build/main/services/inspector.js:3:19)
1|server  |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
1|server  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
1|server  |   code: 'ERR_INSPECTOR_NOT_AVAILABLE'
1|server  | }
PM2       | App [server:1] exited with code [1] via signal [SIGINT]
PM2       | App [server:1] starting in -fork mode-
PM2       | App [server:1] online
1|server  | inspector.js:25
1|server  |   throw new ERR_INSPECTOR_NOT_AVAILABLE();
1|server  |   ^
1|server  | Error [ERR_INSPECTOR_NOT_AVAILABLE]: Inspector is not available
1|server  |     at inspector.js:25:9
1|server  |     at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:283:7)
1|server  |     at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:225:10)
1|server  |     at loadNativeModule (internal/modules/cjs/helpers.js:35:9)
1|server  |     at Function.Module._load (internal/modules/cjs/loader.js:740:15)
1|server  |     at Module.require (internal/modules/cjs/loader.js:952:19)
1|server  |     at require (internal/modules/cjs/helpers.js:88:18)
1|server  |     at Object.<anonymous> (/usr/lib/node_modules/pm2/node_modules/@pm2/io/build/main/services/inspector.js:3:19)
1|server  |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
1|server  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
1|server  |   code: 'ERR_INSPECTOR_NOT_AVAILABLE'
1|server  | }
PM2       | App [server:1] exited with code [1] via signal [SIGINT]
PM2       | Script /home/hs/jd/panel/server.js had too many unstable restarts (16). Stopped. "errored"

**Comment by EvineDeng** [comment]
看起来像是你这个小版本的node有问题，尝试参考faq解决看有没有效。

**Comment by hs20073** [comment]
> 看起来像是你这个小版本的node有问题，尝试参考faq解决看有没有效。

新入门没什么头绪去解决呢😅另外就是jd_crazy_joy_coin和控制面板开一个就会停了另外一个的服务呢😅

**Comment by sallyciel** [comment]
重装一下pm2 试试

**Comment by hs20073** [comment]
> 重装一下pm2 试试

尝试过了，没有解决
