### ISSUE TITLE
git_pull更新LXK9301脚本失败

### ISSUE THREAD

**Issue by znz722** [EvineDeng/jd-base#301]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：

## 3. 按照以下哪个教程做的

- [ ] Linux
- [x] Android
- [ ] MacOS
- [ ] Docker

### (1) 具体问题
A：突然间更新LXK9301脚本失败，手动重试也不行

### (2) 详细日志
A：更新LXK9301脚本，原地址：https://github.com/LXK9301/jd_scripts

Fetching origin
error: insufficient permission for adding an object to repository database .git/objects
fatal: failed to write object
fatal: unpack-objects failed
error: Could not fetch origin
HEAD is now at c9ac33f Merge pull request #222 from FanchangWang/master

### (1) Node.js版本

A：v12.18.3

### (2) npm版本

A：6.14.6

### (3)npm install的日志

A：audited 206 packages in 3.451s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by EvineDeng** [comment]
你自己翻译下这个error。

**Comment by znz722** [comment]
> 你自己翻译下这个error。

更改权限一直失败

> 你自己翻译下这个error。

更改权限一直失败，网上方法用了个遍，求教，也疑惑之前可以，没操作什么为什么就突然开始不行了

**Comment by EvineDeng** [comment]
那就从头来一遍吧。

**Comment by fjqken** [comment]
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'download'
Require stack:
- /home/myid/jd/scripts/jd_bean_sign.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/myid/jd/scripts/jd_bean_sign.js:16:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/myid/jd/scripts/jd_bean_sign.js' ]
}

**Comment by fjqken** [comment]
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'download'
Require stack:
- /home/myid/jd/scripts/jd_bean_sign.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/myid/jd/scripts/jd_bean_sign.js:16:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/myid/jd/scripts/jd_bean_sign.js' ]
}
大佬为什么报这个错，没动过，这两天突然就不行了
