### ISSUE TITLE
测试运行报错,日志为空

### ISSUE THREAD

**Issue by gyq180** [EvineDeng/jd-base#36]
[root@VM-NY15 shell]# bash jd_bean_sign.sh
/root/JD/scripts/jd_bean_sign.js:27
!(async() => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

前面步骤都正常

**Comment by EvineDeng** [comment]
疑似你没按部署环境这部分操作，或者是操作了但没成功。

请提供系统及版本 、运行命令、以及运行命令后的结果，以作进一步判断。

**Comment by gyq180** [comment]
> 你应该是运行git_pull.sh时就没有完全成功，初步怀疑是其中的npm install不成功，我明天修改下相关代码，你删掉重新部署下。

大佬我解决了,好像是node版本太旧了,我安装上最新的没有报错了

**Comment by EvineDeng** [comment]
好
