### ISSUE TITLE
您好，我想请问一下docker模式多用户并行需要什么额外配置吗？

### ISSUE THREAD

**Issue by as48511201** [EvineDeng/jd-base#42]
我尝试创建不同容器映射了不同目录 然后在不同容器内安装教程配置了 但是签到那里就出问题了 
显示如下

🔔京豆签到, 开始!

❗️京豆签到, 错误!
RequestError: connect ECONNREFUSED 151.101.228.133:443
    at ClientRequest.<anonymous> (/root/scripts/node_modules/download/node_modules/got/index.js:182:22)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at TLSSocket.socketErrorListener (_http_client.js:428:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

🔔京豆签到, 结束! 🕛 9.153 秒

**Comment by EvineDeng** [comment]
每个容器内都手动运行过一次git_pull.sh了吗，手动运行的目的是安装npm依赖包。

**Comment by as48511201** [comment]
是的 手动更新过一次了

**Comment by EvineDeng** [comment]
> 是的 手动更新过一次了

看起来不太正常，是在容器内运行的git_pull.sh吗，如果是并且还有问题，你在容器中如下操作一遍再看看：

```
cd /root/scripts
npm install
```
检查一下执行脚本有没有问题，如果还有，重新一下容器试试。

**Comment by as48511201** [comment]
~/scripts # npm install
audited 205 packages in 3.096s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
跟我更换了 npm源有关系吗  我之前一直卡住 然后更换到了taobao的npm源

**Comment by EvineDeng** [comment]
> ~/scripts # npm install
> audited 205 packages in 3.096s
> 
> 11 packages are looking for funding
> run `npm fund` for details
> 
> found 0 vulnerabilities
> 跟我更换了 npm源有关系吗 我之前一直卡住 然后更换到了taobao的npm源

脚本也会在npm install失败时切的到淘宝源的。

手动运行过npm install之后脚本执行如何？

**Comment by as48511201** [comment]
我npm install之后重启了容器 现在貌似可以了

**Comment by as48511201** [comment]
我npm install之后重启了容器 现在貌似可以了

**Comment by as48511201** [comment]
非常感谢！！！

**Comment by EvineDeng** [comment]
``
