### ISSUE TITLE
11.15日新版 测试运行时报错

### ISSUE THREAD

**Issue by fulibus** [EvineDeng/jd-base#48]
[root@iZclu6ttfybsinZ shell]# bash jd_bean_sign.sh
/home/myid/jd1/scripts/jd_bean_sign.js:27
!(async() => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
[root@iZclu6ttfybsinZ shell]#

**Comment by EvineDeng** [comment]
这个错误似乎是js脚本哪里遇到错误了，应该不是shell脚本的问题，你换换其他js脚本运行试试？

**Comment by fulibus** [comment]
> 这个错误似乎是js脚本哪里遇到错误了，应该不是shell脚本的问题，你换换其他js脚本运行试试？

[root@iZclu6ttfybsinZ shell]# bash jd_shop.sh
/home/myid/jd1/scripts/jd_shop.js:35
!(async () => {
        ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
[root@iZclu6ttfybsinZ shell]# 


所有的都是出错。
我用上一个版本的是可用的，今天重新搞了一下就报错，感谢回复

**Comment by EvineDeng** [comment]
你看看jd_shop.sh这个文件第一行的解释器是/bin/sh还是/bin/bash？
如果是前者，就改成后者，在和scripts一层级的地方重新运行一次first_run.sh，可以重新替换所有原来的.sh文件。

**Comment by fulibus** [comment]
是    #!/bin/bash  重新first run 依旧，

我重装一下看看，是不是我自己的问题

**Comment by EvineDeng** [comment]
嗯，我手机、ubuntu和docker都试了，都是好的。

**Comment by fulibus** [comment]
换了ubuntu  又测试了两遍，还是不行。。
等一两天看看别人反馈，感谢大佬。

**Comment by EvineDeng** [comment]
你可以试一下在scripts文件下直接使用类似`node  jd_shop.js`之类的命令直接运行js脚本看看报错不报错，如果还报错，运行一下`npm install`之后再重新运行`node  jd_shop.js`试试。

**Comment by fulibus** [comment]
> 你可以试一下在scripts文件下直接使用类似`node jd_shop.js`之类的命令直接运行js脚本看看报错不报错，如果还报错，运行一下`npm install`之后再重新运行`node jd_shop.js`试试。
> 
> 如果直接运行js报错，那么运行sh也会报错，如何运行js不报错，那么运行sh应该也不会报错。

容器版安装成功，估计是npm install 这一步的问题

**Comment by EvineDeng** [comment]
已经知道原因，请见：https://github.com/EvineDeng/jd-base/wiki/FAQ
