### ISSUE TITLE
armbian 5.88，执行bash jd_bean_sign.sh时报错

### ISSUE THREAD

**Issue by fdfangzhou** [EvineDeng/jd-base#55]
root@aml:/home/jd/shell# bash jd_bean_sign.sh
/home/jd/scripts/jd_bean_sign.js:52
    .finally(() => $.done())
            ^

TypeError: (intermediate value)(...).catch(...).finally is not a function
    at Object.<anonymous> (/home/jd/scripts/jd_bean_sign.js:52:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by EvineDeng** [comment]
自己看FAQ

**Comment by fdfangzhou** [comment]
初步判定是nodejs版本<10导致的
