### ISSUE TITLE
telegram发送通知消息失败！！

### ISSUE THREAD

**Issue by 68cs** [EvineDeng/jd-base#67]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台，精确到版本
A：armV8

## 3. 按照以下哪个教程做的

- [ ] Linux
- [ ] Android
- [ ] MacOS
- [x] Docker

### (1) 具体问题
A：telegram发送通知消息失败！！

### (2) 详细日志
A：telegram发送通知消息失败！！

RequestError: connect ETIMEDOUT 192.133.77.145:443
    at ClientRequest.<anonymous> (/root/scripts/node_modules/got/dist/source/core/index.js:953:111)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:326:22)
    at ClientRequest.origin.emit (/root/scripts/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:428:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16) {
  code: 'ETIMEDOUT',
  timings: {
    start: 1605970053117,
    socket: 1605970053124,
    lookup: 1605970053131,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1605970183835,
    abort: undefined,
    phases: {
      wait: 7,
      dns: 7,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 130718

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
tg需要科学上网环境才可以发送，如不具备，建议放弃tg。
